### ISSUE TITLE
Altair

### ISSUE THREAD

**Issue by toni-chess** [Alex2262/AltairChessEngine#167]
1-Altair make often illegal move!

[White "Houdini 6.03 x64"]
[Black "Altair 7.0.0 x64"]

....... 77. Kh2 {-0.45/7 0} Qa6 {+1.00/15 0}
78. Kg1 {-0.75/9 0} Qa5 {+0.97/13 0} 79. Kg2 {-0.79/7 0  Arena
Adjudication. Illegal move!} 1-0

---------------------------------

2-Altair crash on quit...
Sandboxie message:
SBIE2101 Object name not found: Unnamed object, error OpenProcess (C0000022) access=001FFFFF initialized=1

thankyou!

**Comment by Alex2262** [comment]
Hi,

Can you provide some more details on how Altair crashed or made illegal moves? Such as, what OS you were using, GUI, executable/binary, and settings on Altair?

During testing, Altair 7 has never crashed nor made illegal moves, and this issue has never occurred with others either. I would rather assume there is an issue with how you are running Altair rather than the engine itself. Either way, thanks for the issue post!

**Comment by toni-chess** [comment]
Hi! 
Thank for respond and congratulations for your chess engine!
----------------------
Country=Greece
Hardware=Intel(R) Core(TM) i5-4570 3.20GHz 8GB RAM
OS=Windows 10 Pro x64
GUI=Arena 3.5.1
-----------------------------------------
Level=2 0\9/0#100(Timecontrol: 9s+0,1 per game )

[Altair 7.0.0 x64(AVX2)]
Hash=16
Threads=1
-------------
I test chess engines only on Sandbox.

here is an part of some game

[White "Carp 3.0.1 x64(AVX2-5Pct)"]
[Black "Altair 7.0.0 x64(AVX2-5Pct)"]
......
98. Kc1 Qb5 {+M2/87 0} 99. Kd1 {Arena Adjudication. Illegal move!} 1-0
